/**
 * A small Markdown renderer for coach answers.
 *
 * Deliberately hand-rolled rather than pulling in a library: the coach's output
 * is generated by this application's own templates, so only a fixed subset is
 * ever produced — paragraphs, bold, lists, tables and code fences.
 *
 * It renders through React elements rather than `dangerouslySetInnerHTML`, so
 * text coming back from a language model cannot inject markup.
 */

import type { ReactNode } from 'react';

/** Bold spans, split without any HTML parsing. */
function inline(text: string, keyPrefix: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*)/g).map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      return (
        <strong key={`${keyPrefix}-${i}`} className="font-semibold text-ink">
          {part.slice(2, -2)}
        </strong>
      );
    }
    return part;
  });
}

function splitRow(line: string): string[] {
  return line
    .replace(/^\||\|$/g, '')
    .split('|')
    .map((cell) => cell.trim());
}

const isSeparator = (line: string) => /^\|?[\s:|-]+\|[\s:|-]*$/.test(line) && line.includes('-');

export function Markdown({ content }: { content: string }) {
  const lines = content.split('\n');
  const blocks: ReactNode[] = [];

  let i = 0;
  let key = 0;

  while (i < lines.length) {
    const line = lines[i];

    // --- Code fence ------------------------------------------------------
    if (line.trim().startsWith('```')) {
      const body: string[] = [];
      i++;
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        body.push(lines[i]);
        i++;
      }
      i++;
      blocks.push(
        <pre
          key={key++}
          className="overflow-x-auto rounded-lg border border-line bg-base p-3 text-xs text-ink-muted"
        >
          <code>{body.join('\n')}</code>
        </pre>,
      );
      continue;
    }

    // --- Table -----------------------------------------------------------
    if (line.includes('|') && i + 1 < lines.length && isSeparator(lines[i + 1])) {
      const header = splitRow(line);
      i += 2;
      const rows: string[][] = [];
      while (i < lines.length && lines[i].includes('|') && lines[i].trim() !== '') {
        rows.push(splitRow(lines[i]));
        i++;
      }

      blocks.push(
        <div key={key++} className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-line text-left">
                {header.map((cell, c) => (
                  <th key={c} className="whitespace-nowrap px-2 py-1.5 font-medium text-ink-faint">
                    {cell}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, r) => (
                <tr key={r} className="border-b border-line/50 last:border-0">
                  {row.map((cell, c) => (
                    <td key={c} className="tnum whitespace-nowrap px-2 py-1.5 text-ink-muted">
                      {inline(cell, `${r}-${c}`)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>,
      );
      continue;
    }

    // --- List ------------------------------------------------------------
    if (/^\s*[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\s*[-*]\s+/, ''));
        i++;
      }
      blocks.push(
        <ul key={key++} className="space-y-1 pl-4">
          {items.map((item, index) => (
            <li key={index} className="list-disc text-ink-muted marker:text-ink-faint">
              {inline(item, `li-${index}`)}
            </li>
          ))}
        </ul>,
      );
      continue;
    }

    // --- Blank line ------------------------------------------------------
    if (line.trim() === '') {
      i++;
      continue;
    }

    // --- Paragraph -------------------------------------------------------
    const paragraph: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== '' &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !lines[i].trim().startsWith('```') &&
      !(lines[i].includes('|') && i + 1 < lines.length && isSeparator(lines[i + 1]))
    ) {
      paragraph.push(lines[i]);
      i++;
    }

    blocks.push(
      <p key={key++} className="leading-relaxed text-ink-muted">
        {inline(paragraph.join(' '), `p-${key}`)}
      </p>,
    );
  }

  return <div className="space-y-3 text-sm">{blocks}</div>;
}
